site_name: LovinData - Simplified Full Stack Data Engineering
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
      primary: black
    - scheme: slate
      toggle:
        icon: material/toggle-switch
      primary: black
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
plugins:
  - blog:
      blog_dir: .
  - search
  - tags
  - glightbox
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lovindata
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/jamesjg/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repositories/lovindata
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jamesjg_
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/james-jiang-87306b155/
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/lovindata/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@jamesjg
copyright: Copyright &copy; <script>document.write(new Date().getFullYear())</script> James Jiang
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  # Markdown in HTML
  - md_in_html
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
