apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-sa-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch", "create", "deletecollection"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "deletecollection"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "deletecollection"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["list", "deletecollection"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-sa-rolebinding
subjects:
  - kind: ServiceAccount
    name: spark-sa
roleRef:
  kind: Role
  name: spark-sa-role
  apiGroup: rbac.authorization.k8s.io