name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: blog
          environment-file: environment.yml
          auto-activate-base: false
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - shell: bash
        run: conda info
      - shell: bash
        run: conda list
      - shell: bash
        run: conda config --show
      - shell: bash
        run: mkdocs gh-deploy --force
